spring:
  datasource:
    url: jdbc:mysql://mysql.goofood:3306/goodfood_authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka.goodfood:9092
