server:
  port: 8090

spring:
  application:
    name: goodfood-gateway

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true   # useful for Kubernetes liveness/readiness
  metrics:
    tags:
      application: ${spring.application.name}
      service-type: gateway
  tracing:
    sampling:
      probability: 1.0

