server:
  port: 8085

spring:
  application:
    name: goodfood-delivery-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true   # useful for Kubernetes liveness/readiness
  metrics:
    tags:
      application: ${spring.application.name}
      service-type: delivery
  tracing:
    sampling:
      probability: 1.0
