spring:
  datasource:
    url: jdbc:mysql://mysql.goodfood.svc.cluster.local:3306/goodfood_deliverydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  kafka:
    bootstrap-servers: kafka.goodfood.svc.cluster.local:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server.goodfood.svc.cluster.local:9000/oauth2/jwks
