spring:
  application:
    name: goodfood-auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/goodfood_authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123

