spring:
  cloud:
    gateway:
      routes:
        # - id: auth-server
        #   uri: http://auth-server.goodfood.svc.cluster.local:9000
        #   predicates:
        #     - Path=/auth/**,/oauth2/**
        # - id: order-service
        #   uri: http://order-service.goodfood.svc.cluster.local:8082
        #   predicates:
        #     - Path=/orders/**
        # - id: restaurant-service
        #   uri: http://restaurant-service.goodfood.svc.cluster.local:8084
        #   predicates:
        #     - Path=/restaurants/**
        # - id: delivery-service
        #   uri: http://delivery-service.goodfood.svc.cluster.local:8085
        #   predicates:
        #     - Path=/deliveries/**
        - id: auth-server
          uri: http://${AUTH_SERVER_URL}:9000
          predicates:
            - Path=/auth/**,/oauth2/**
        - id: order-service
          uri: http://${ORDER_SERVICE_URL}:8082
          predicates:
            - Path=/orders/**
        # - id: restaurant-service
        #   uri: http://${RESTAURANT_SERVICE_URL}:8084
        #   predicates:
        #     - Path=/restaurants/**
        # - id: delivery-service
        #   uri: http://${DELIVERY_SERVICE_URL}:8085
        #   predicates:
        #     - Path=/deliveries/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_SERVER_URL}:9000/oauth2/jwks

  # zipkin:
  #   base-url: http://zipkin.goodfood.svc.cluster.local:9411
