spring:
  # datasource:
  #   url: jdbc:mysql://mysql.goodfood.svc.cluster.local:3306/goodfood_orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #   username: root
  #   password: ${DB_PASSWORD}
  datasource:
    url: jdbc:mysql://goodfood.c106ugc8gvds.ap-south-1.rds.amazonaws.com:3306/goodfood_orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # kafka:
  #   bootstrap-servers: kafka.goodfood.svc.cluster.local:9092
  #   producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER_URL}:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: http://auth-server.goodfood.svc.cluster.local:9000/oauth2/jwks

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_SERVER_URL}:9000/oauth2/jwks


  # zipkin:
  #   base-url: http://zipkin.goodfood.svc.cluster.local:9411
