spring:
  datasource:
    url: jdbc:mysql://mysql:3306/goodfood_deliverydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks

  zipkin:
    base-url: http://zipkin:9411
