spring:
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**,/oauth2/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: restaurant-service
          uri: http://localhost:8084
          predicates:
            - Path=/restaurants/**
        - id: delivery-service
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
