server:
  port: 8082

spring:
  application:
    name: goodfood-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
