server:
  port: 8084

spring:
  application:
    name: goodfood-restaurant-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true   # useful for Kubernetes liveness/readiness
  metrics:
    tags:
      application: ${spring.application.name}
      service-type: restaurant
  # tracing:
  #   sampling:
  #     probability: 1.0
